# Generated by Django 6.1 on 2026-09-05 01:31

import pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_paqueteturistico_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes/'),
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[pedidos.models.validar_precio_positivo]),
        ),
    ]
